# Generated by Django 4.0.3 on 2022-04-25 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('age_rating', models.CharField(choices=[('12+', '12+'), ('15+', '15+'), ('18+', '18+'), ('PG-13', 'PG-13')], default='string', max_length=7)),
                ('duration', models.IntegerField(null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_id', models.IntegerField()),
                ('seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UniversityClub',
            fields=[
                ('auto_increment_club_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=200, null=True)),
                ('street_number', models.IntegerField(null=True)),
                ('street', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('postcode', models.CharField(max_length=200, null=True)),
                ('telephone', models.IntegerField(null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('debit_amount', models.IntegerField(null=True)),
                ('club_rep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uweflixapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uweflixapp.film')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uweflixapp.screen')),
            ],
        ),
        migrations.CreateModel(
            name='ClubRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('password', models.CharField(max_length=8, null=True, unique=True)),
                ('club_rep_id', models.CharField(max_length=6, null=True, unique=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uweflixapp.universityclub')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_quantity', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uweflixapp.customer')),
                ('showing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uweflixapp.showing')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('card_number', models.IntegerField()),
                ('expiry_date', models.IntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uweflixapp.universityclub')),
            ],
        ),
    ]
