# Generated by Django 4.0.3 on 2022-04-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uweflixapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='screen_id',
            field=models.CharField(max_length=50),
        ),
    ]
