# Generated by Django 4.0.3 on 2022-05-05 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uweflixapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingShowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uweflixapp.booking')),
                ('showing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uweflixapp.showing')),
            ],
        ),
    ]
