# Generated by Django 4.0.4 on 2022-05-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uweflixapp', '0002_alter_movie_age_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='type',
        ),
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('account_manager', 'Account Manager'), ('club_rep', 'Club Representative'), ('student', 'Student')], max_length=20, null=True),
        ),
    ]
