# Generated by Django 4.0.3 on 2022-05-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uweflixapp', '0002_alter_booking_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_cost',
            field=models.FloatField(default=0),
        ),
    ]
