# Generated by Django 4.0.4 on 2022-05-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uweflixapp', '0002_club_alter_showing_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='club',
            field=models.ManyToManyField(to='uweflixapp.club'),
        ),
    ]
