# Generated by Django 4.0.3 on 2022-05-08 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uweflixapp', '0003_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
    ]
