# Generated by Django 4.0.4 on 2022-05-09 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uweflixapp', '0003_customuser_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='club',
        ),
        migrations.AddField(
            model_name='showing',
            name='discount',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='Club',
        ),
    ]
