# Generated by Django 4.0.3 on 2022-05-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uweflixapp', '0003_alter_booking_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_cost',
            field=models.FloatField(null=True),
        ),
    ]
