# Generated by Django 4.0.4 on 2022-05-09 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uweflixapp', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='manager',
            new_name='account_manager',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='rep',
            new_name='club_epresentitive',
        ),
    ]
