# Generated by Django 4.0.3 on 2022-05-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uweflixapp', '0004_remove_user_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='postcode',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='street_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
    ]
