# Generated by Django 4.0.4 on 2022-05-09 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uweflixapp', '0005_remove_showing_discount_customuser_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
