# Generated by Django 4.0.4 on 2022-05-09 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uweflixapp', '0005_rename_manager_customuser_account_manager_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='club_epresentitive',
            new_name='club_representitive',
        ),
    ]
