# Generated by Django 4.0.3 on 2022-05-08 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uweflixapp', '0005_user_city_user_mobile_user_postcode_user_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityclub',
            name='club_rep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
