# Generated by Django 4.0.3 on 2022-05-06 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uweflixapp', '0006_alter_booking_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ticket_quantity',
        ),
    ]
