# Generated by Django 4.0.3 on 2022-05-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uweflixapp', '0006_alter_universityclub_club_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showing',
            name='available_seats',
            field=models.IntegerField(default=100),
        ),
    ]
