# Generated by Django 4.0.3 on 2022-05-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uweflixapp', '0007_remove_booking_ticket_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='available_seats',
            field=models.IntegerField(default=200),
        ),
    ]
