# Generated by Django 4.0.3 on 2022-05-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uweflixapp', '0009_alter_booking_adult_ticket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_cost', models.FloatField()),
                ('child_cost', models.FloatField()),
                ('student_cost', models.FloatField()),
                ('club_discout', models.FloatField()),
                ('student_discount', models.FloatField()),
            ],
        ),
    ]
