# Generated by Django 4.0.3 on 2022-05-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uweflixapp', '0010_costs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costs',
            new_name='Cost',
        ),
    ]
