# Generated by Django 4.0.3 on 2022-05-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uweflixapp', '0012_alter_cost_club_discout_alter_cost_student_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='student_cost',
        ),
    ]
