# Generated by Django 4.0.3 on 2022-05-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uweflixapp', '0013_remove_cost_student_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost',
            old_name='club_discout',
            new_name='club_discount',
        ),
    ]
