# Generated by Django 4.0.3 on 2022-05-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uweflixapp', '0014_rename_club_discout_cost_club_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distancing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toggle_distancing', models.BooleanField(default=False)),
            ],
        ),
    ]
